name: deploy via ssh

on:
  push:
    branches:
      - main

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
    - name: checkout code
      uses: actions/checkout@v3

    - name: setup ssh key
      uses: webfactory/ssh-agent@v0.9.0
      with:
        ssh-private-key: ${{ secrets.SSH_PRIVATE_KEY }}

    - name: build + deploy
      run: |
        ssh -o StrictHostKeyChecking=no ${{ secrets.SSH_USERNAME }}@${{ secrets.SSH_HOST }} << 'EOF'
        export NVM_DIR="/home/${{ secrets.SSH_USERNAME }}/.nvm"
        export PATH="$NVM_DIR/versions/node/v20.14.0/bin:$PATH"
        cd /apps/icarus-web
        git pull
        /home/${{ secrets.SSH_USERNAME }}/.nvm/versions/node/v20.14.0/bin/yarn
        /home/${{ secrets.SSH_USERNAME }}/.nvm/versions/node/v20.14.0/bin/yarn build
        EOF
